Added justification to the modified tolerance value
ROCmSoftwarePlatform/rocBLAS-Examples pull request #47
Opened 2020-10-16 16:36 UTC by NaveenElumalaiAMD

Made few changes in the code to replace 'max_relative_error' to 'max_error' and added 'allowed error' = eps * 10 * K * sqrt(K). Added Justification to the calculation of 'allowed error' in README. This is a follow up to the [PR](https://github.com/ROCmSoftwarePlatform/rocBLAS-Examples/pull/45).

2020-10-16 18:37 UTC, amcamd approved these changes
LGTM

2020-10-19 13:45 UTC, amcamd approved these changes
LGTM

2020-10-19 18:27 UTC, TorreZuk requested changes
The grep is only on the output, your variables were fine.

2020-10-19 18:35 UTC, NaveenElumalaiAMD commented
Oh okay. I modified the std::cout message. Thanks

2020-10-19 18:40 UTC, TorreZuk approved these changes
"max. err. " might be better but that is fine by me.

2020-10-19 18:59 UTC, merged